changelog:
  exclude:
    labels:
      - test-dependency-updates
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - new-feature
    - title: Bug fixes
      labels:
        - bug-fix
    - title: Dependency updates
      labels:
        - dependency-updates
        - dependencies
    - title: Others
      labels:
        - chore
        - "*"