name: run-tests

on:
  workflow_call:
    outputs:
      pr_number:
        description: "The PR number"
        value: ${{ jobs.test.outputs.pr_number }}
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    outputs:
      pr_number: ${{ github.event.number }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - uses: actions/checkout@v3
      - env:
          ARM_SUBSCRIPTION_ID: "FAKE_ARM_SUBSCRIPTION_ID_NEEDED_FOR_INTEGRATION_TESTS"
          ARM_TENANT_ID: "FAKE_ARM_TENANT_ID_NEEDED_FOR_INTEGRATION_TESTS"
          ARM_CLIENT_ID: "FAKE_ARM_CLIENT_ID_NEEDED_FOR_INTEGRATION_TESTS"
          ARM_CLIENT_SECRET: "FAKE_ARM_CLIENT_SECRET_NEEDED_FOR_INTEGRATION_TESTS"
      - run: make test
  call-dependabot-pr-workflow:
    needs: test
    if: ${{ success() && github.actor == 'dependabot[bot]' }}
    uses: cloudfoundry/cloud-service-broker/.github/workflows/dependabot-test.yml@main
    with:
      pr_number: ${{ github.event.number }}
